# Generated by Django 2.2.8 on 2022-10-18 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221018_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='catagory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=512), default=None, size=None),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_turf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='turf_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
