<<<<<<< HEAD
# Generated by Django 2.2.8 on 2022-10-19 10:58
=======
# Generated by Django 2.2.8 on 2022-10-20 10:45
>>>>>>> 1d48d9d1bbe3fda2651df667d4a6cbf8dcf51744

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creatematchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
<<<<<<< HEAD
                ('nos', models.PositiveIntegerField(default=0)),
=======
                ('nos', models.IntegerField()),
>>>>>>> 1d48d9d1bbe3fda2651df667d4a6cbf8dcf51744
                ('avs', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
